apiVersion: v1
kind: Pod
metadata:
  name: webserver
spec:
  containers:
    - image: apcerademos/aws-webserver
      name: webserver
      ports:
        - containerPort: 9100
          name: http
          protocol: TCP
